- 👋 Hi, I am a 24-year-old developer, who loves games, Unity, and C#
- 👀 I’m interested in the development of applications or games.
- 🌱 I’m currently learning how to be much better in Unity
- 💞️ I’m looking to collaborate on anything in C#
- 📫 How to reach me - email: bonnyas.as.199@gmial.com
